name: SARS2-prot-sub-counts
channels:
  - conda-forge
  - defaults
  - bioconda

dependencies:
  - altair=4.2
  - biopython=1.79
  - entrez-direct=16.2
  - jupyterlab
  - pandas=1.4.2
  - pip
  - python=3.9
  - usher=0.5.6
  - snakemake=7.12.1
